---
title: DefundIR.org
timezone: UTC
collections:
  emails:
    title: Emails
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: emails
  values:
    layout: email
    permalink: "/desired-path"
    name: Title of letter (e.g. Letter to City Council)
    city: City
    state: State intials
    recipients:
    - 
    subject: Email subject (mention defunding police dept.)
    body: Email message (remember to include placeholders for name)
siteTitle: DefundIR.org
permalink: pretty
subtitle: Email government officials to demand that they stand with the 
  people of Iran against the regime of the Islamic Republic.. Demand that they recognizing the Islamic 
  Republic as an illegitimate government and the Islamic Revolutionary Guards Corps as a terrorist organization.
meta: Email government officials to demand that they stand with the 
  people of Iran against the regime of the Islamic Republic. Cut all diplomatic ties and stand with the people of Iran
  in fighting for their freedom.
footerTextPr: Want to add your city? [Open a request.](https://github.com/defund12/defund12.org/issues)
footerTextInstructions: Have the emails of your city government officials and a drafted
  template ready.
contactEmailFooter: "[opirantech@gmail.com](mailto:opirantech@gmail.com)"
defaultSubjectLine: "[*** INSERT UNIQUE SUBJECT LINE ***]"
autoOpenMessage: This page automatically opens a drafted email for you.
badMailtoMessage: Email link not working correctly? You can copy and paste the recipients,
  subject and message individually below.
url: https://defund12.org
logoUrl: "/images/logoir.png"
faviconUrl: "/favicon.jpg"
metaPreviewUrl: https://defund12-image-api.now.sh/api/preview/
sass:
  sass_dir: _sass
  style: compressed
letterPageHeader: NOTE sending physical mail incurs a small fee of $1/letter. Read
  more about how it works [here](https://github.com/defund12/defund12-api/blob/master/README.md).
googleApiKey: AIzaSyAiQLnfziASZ6GGByNDLV3E7WkhtOtfi9s
